package date2020_02_27;

public enum MenuOption {
    HOW_MANY_MONDAYS_UNTIL,
    HOW_MANY_MONDAYS_SINCE_UNTIL,
    HOW_MANY_MONADYS_SINCE_1900,
    LAST_MONDAY_OF_YEAR,
    DAYS_UNTIL,
    GET_WEEKDAY_OF_DATE,
    PALINDROME_DATE,
    HOW_MANY_MONDAYS_IN_YEAR,
    INVALID,
    END
}
